knp_snappy:
  pdf:
    enabled:    true
    binary:     /usr/bin/wkhtmltopdf
    options:
      no-outline: true
      page-size: LETTER
      encoding: UTF-8
  image:
    enabled:    true
    binary:     /usr/bin/wkhtmltoimage
    options: []


